### PR TITLE
Add missing p tag

### PR DESCRIPTION
**Pull request by dcadenas**
I extracted the change for the `p` tag from https://github.com/planetary-social/cleanstr/pull/40 so we can merge independently

### CODE REVIEW

**Comment by dcadenas** [comment]
I'm not sure if this could break the app so better to have a proper review

**Comment by mplorentz** [comment]
Here is the iOS bug ticket if you want to watch it:
https://github.com/planetary-social/nos/issues/997

**Comment by dcadenas** [comment]
Cool, I will wait for @setch-l green light to merge

**Comment by setch-l** [comment]
@dcadenas - You can merge this. I moved the other bug to the top of the Delivery Backlog

**Pull request merged**
